export const en = {
    Home:'Home',
    Resume:'Resume',
    Portfolio:'Portfolio',
    Contact:'Contact',
    diyorbek:"Diyorbek",
    hobby : 'Web developer study TUIT in Tashkent',
    about:"Hi, I'm",
    hobbywork:'Web developer',
    location:'Tashkent',
    download:'Download my curriculum vitae:',
    downloadCv:'DOWNLOAD CV',
    contactMe:'CONTACT ME',
    languageEn:"English",
    myResume:'My Resume',
    education:'Education',
    skills:'Professional Slills',
    educationFirst:'I am currently a 2nd year student at TATU',
    educationSecond:'I studied at a specialized school in Chust district of Namangan region',
    educationThird:'I studied at zako IT Academy center',
    bachelour:'Bachelour TUIT',
    course:'Course - IT',
    educationDescFirst:'Tashkent University of Information Technologies, Telecommunications: Telecommunication technologies.',
    educationSecondDesc:'64th general secondary school of Chust district of Namangan region',
    educationCourseDesc:'Amir Temur street, Yunusabad district,',
    locationCourse:'Tashkent city',
    recording:'Recording...',
    myPortfolio:'My Portfolio',
    myContact:'My Contact',
    locationLan:'Location',
    email:'Email',
    phone:'Phone',
    link:'FIND WITH ME',
    name:'YOUR NAME',
    number:'PHONE NUMBER',
    emailContact:'EMAIL',
    subject:'SUBJECT',
    message:'YOUR MESSAGE',
    sendMessage:'SEND MESSAGE'
}