export const ru = {
    Home:'Основной',
    Resume:'Резюме',
    Portfolio:"Портфолио",
    Contact:'Контакты',
    languageRu:'Русский',
    diyorbek:"Диёрбек",
    hobby:'Веб-разработчик учится в TUIT в Ташкенте',
    about:'Привет , Я',
    hobbywork:'Веб-разработчик',
    location:'Ташкент',
    download:'Скачать мою биографическую справку:',
    downloadCv:'СКАЧАТЬ РЕЗЮМЕ',
    contactMe:'СВЯЖИТЕСЬ СО МНОЙ',
    myResume:'Mое Pезюме',
    education:'Образование',
    skills:'Профессиональные Навыки',
    educationFirst:'В настоящее время я учусь на 2 курсе ТАТУ',
    educationSecond:'Я учился в специализированной школе в Чустском районе Наманганской области',
    educationThird:'Я учился в центре zako IT Academy center',
    bachelour:'Бакалавриате в ТУИТе',
    course:'Курсы - IT',
    educationDescFirst:'Ташкентский университет информационных технологий, Телекоммуникации: Телекоммуникационные технологии.',
    educationSecondDesc:'64-я общеобразовательная средняя школа Чустского района Наманганской области',
    educationCourseDesc:'Улица Амира Темура, Юнусабадский район,',
    locationCourse:'Город Ташкент',
    recording:'Запись...',
    myPortfolio:'Портфолио',
    myContact:'Контакт',
    locationLan:'Mестоположение',
    email:'Электронная почта',
    phone:'Tелефон',
    link:'НАЙДИ МЕНЯ'
}