export const uz = {
    Home:'Asosiy',
    Resume:'Rezume',
    Portfolio:"Ishlarim",
    Contact:'Kontakt',
    languageUz:"Uzbekcha",
    diyorbek:"Diyorbek",
    hobby : 'Web dasturchi Toshkentda TATUda tahsil oladi',
    about : 'Salom,  men',
    hobbywork:'Web dasturchi',
    location:'Tashkent',
    download:"O'quv dasturimni yuklab oling:",
    downloadCv:'REZYUMENI YUKLASH',
    contactMe:"KONTAKTGA BOGLANISH",
    myResume:'Rezyume',
    education:'Talim',
    skills:'Kasbiy malaka',
    educationFirst:'Hozirda TATU 2-kurs talabasiman',
    educationSecond:'Namangan viloyati Chust tumanidagi ixtisoslashtirilgan maktabda tahsil oldim',
    educationThird:'Men zako IT Academy markazida tahsil oldim',
    bachelour:'Bakalavr kurs',
    course:'IT Kurs',
    educationDescFirst:'Toshkent axborot texnologiyalari universiteti, telekommunikatsiyalar: Telekommunikatsiya texnologiyalari.',
    educationSecondDesc:"Namangan viloyati Chust tumanidagi 64-umumiy o’rta ta’lim maktabi",
    educationCourseDesc:"Toshkent shahri, Yunusobod tumani",
    locationCourse:' Amir Temur ko‘chasi',
    recording:'Yozib olish...',
    myPortfolio:'Ishlarim',
    myContact:'Kontakt',
    locationLan:'Lokatsiya',
    email:'Email',
    phone:'Telefon',
    link:'MENI TOPING',
    name:'ISMINGIZ',
    number:'TELEFON RAQAMINGIZ',
    emailContact:'EMAILINGIZ',
    subject:'MAVZU',
    message:'SIZNING XABARINGIZ',
    sendMessage:'XABAR YUBORISH'
}